# 应用名称
spring.application.name=spring-reactive-test

# R2DBC MySQL配置
spring.r2dbc.url=r2dbc:mysql://101.132.146.9:3306/bookdb
spring.r2dbc.username=book
spring.r2dbc.password=c2c132b4c38a41eab2102225cfc26718Q@

# MySQL连接池配置
spring.r2dbc.pool.max-size=100
spring.r2dbc.pool.min-idle=20

# 服务器配置
server.port=8080

# 日志级别
logging.level.root=INFO
logging.level.com.book.reactive=DEBUG
# R2DBC SQL日志配置
logging.level.io.r2dbc.spi=DEBUG
logging.level.io.asyncer.r2dbc.mysql=DEBUG
logging.level.org.springframework.r2dbc=DEBUG
logging.level.org.springframework.data.r2dbc=DEBUG

# Redis配置
spring.redis.host=redis
spring.redis.port=6379
spring.redis.password=9e4e9f2ea8f646cc887140a05c149220
spring.redis.database=0

# Reactive Redis连接池配置
spring.redis.lettuce.pool.max-active=20
spring.redis.lettuce.pool.max-wait=1000ms
spring.redis.lettuce.pool.max-idle=200
spring.redis.lettuce.pool.min-idle=0

# JWT配置
jwt.secret=book_reactive_jwt_secret_key_2024

# RabbitMQ配置
spring.rabbitmq.host=rabbitmq
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=bookdb.book

# 章节处理队列配置
chapter.queue.name=chapter_process_queue
chapter.exchange.name=chapter_exchange
chapter.routing.key=chapter.process
# 批处理配置
batch.size=150
batch.timeout=5
# 定时任务配置 15点 30分执行
book.crawl.cron=0 43 18 * * ?